package hurricache

import (
	"context"
	"time"
)

// Operations is the complete shared direct/smart operation interface.
type Operations interface {
	GetValue(ctx context.Context, key []byte, o Options) (ValueResult, error)
	GetAndDeleteValue(ctx context.Context, key []byte, o Options) (ValueResult, error)
	ExistKey(ctx context.Context, key []byte, o Options) (bool, error)
	Remove(ctx context.Context, key []byte, o Options) (bool, error)
	GetSize(ctx context.Context, key []byte, o Options) (uint32, error)
	GetFront(ctx context.Context, key []byte, o Options) (ValueResult, error)
	GetHead(ctx context.Context, key []byte, o Options) (ValueResult, error)
	GetTail(ctx context.Context, key []byte, o Options) (ValueResult, error)
	GetAndRemoveFront(ctx context.Context, key []byte, o Options) (ValueResult, error)
	GetAndRemoveTail(ctx context.Context, key []byte, o Options) (ValueResult, error)
	RemoveHead(ctx context.Context, key []byte, o Options) (bool, error)
	RemoveTail(ctx context.Context, key []byte, o Options) (bool, error)
	AtomicLoad(ctx context.Context, key []byte, o Options) (AtomicResult, error)
	AtomicLoadAndDelete(ctx context.Context, key []byte, o Options) (AtomicResult, error)
	SetTTL(ctx context.Context, key []byte, ttl time.Duration, o Options) (bool, error)
	GetTTL(ctx context.Context, key []byte, o Options) (TTLResult, error)
	CreateKeyValue(ctx context.Context, key []byte, value []byte, o Options) (*KeyHint, error)
	UpdateKeyValue(ctx context.Context, key []byte, value []byte, o Options) (UpdateResult, error)
	GetElementAtPosition(ctx context.Context, key []byte, pos Position, o Options) (ValueResult, error)
	GetAndRemoveElementAtPosition(ctx context.Context, key []byte, pos Position, o Options) (ValueResult, error)
	RemoveElementAtPosition(ctx context.Context, key []byte, pos Position, o Options) (bool, error)
	GetContainerValue(ctx context.Context, key []byte, elementKey []byte, o Options) (ValueResult, error)
	GetAndRemoveContainerValue(ctx context.Context, key []byte, elementKey []byte, o Options) (ValueResult, error)
	ContainsContainerKey(ctx context.Context, key []byte, elementKey []byte, o Options) (bool, error)
	RemoveContainerKey(ctx context.Context, key []byte, elementKey []byte, o Options) (uint32, error)
	UpdateContainerValue(ctx context.Context, key []byte, elementKey, value []byte, o Options) (UpdateResult, error)
	LockObject(ctx context.Context, key []byte, kind LockType, duration time.Duration, o Options) (LockResult, error)
	UnlockObject(ctx context.Context, key []byte, o Options) (LockResult, error)
	AtomicCreate(ctx context.Context, key []byte, value int64, o Options) (*KeyHint, error)
	AtomicStore(ctx context.Context, key []byte, value int64, o Options) (*KeyHint, error)
	AtomicExchange(ctx context.Context, key []byte, value int64, o Options) (AtomicResult, error)
	AtomicAdd(ctx context.Context, key []byte, value int64, o Options) (AtomicResult, error)
	AtomicSub(ctx context.Context, key []byte, value int64, o Options) (AtomicResult, error)
	AtomicOr(ctx context.Context, key []byte, value int64, o Options) (AtomicResult, error)
	AtomicAnd(ctx context.Context, key []byte, value int64, o Options) (AtomicResult, error)
	AtomicXor(ctx context.Context, key []byte, value int64, o Options) (AtomicResult, error)
	AtomicCompareAndSet(ctx context.Context, key []byte, expected, newValue int64, o Options) (CASResult, error)
	CreateContainer(ctx context.Context, key []byte, t ContainerType, data ContainerData, o Options) (*KeyHint, error)
	RemoveFromContainer(ctx context.Context, key []byte, removal Removal, o Options) (uint32, error)
	GetContainer(ctx context.Context, key []byte, o Options) (ContainerData, error)
	GetElementInRange(ctx context.Context, key []byte, pos Position, o Options) (ContainerData, error)
	CreateQueue(ctx context.Context, key []byte, data []Payload, o Options) (*KeyHint, error)
	StreamQueue(ctx context.Context, key []byte, o Options) ([]Payload, error)
	CreateList(ctx context.Context, key []byte, data []Payload, o Options) (*KeyHint, error)
	StreamList(ctx context.Context, key []byte, o Options) ([]Payload, error)
	CreateVector(ctx context.Context, key []byte, data []Payload, o Options) (*KeyHint, error)
	StreamVector(ctx context.Context, key []byte, o Options) ([]Payload, error)
	CreateSet(ctx context.Context, key []byte, data []Payload, o Options) (*KeyHint, error)
	StreamSet(ctx context.Context, key []byte, o Options) ([]Payload, error)
	CreateOrderedSet(ctx context.Context, key []byte, data []OrderedPayload, o Options) (*KeyHint, error)
	StreamOrderedSet(ctx context.Context, key []byte, o Options) ([]OrderedPayload, error)
	CreateMap(ctx context.Context, key []byte, data []Entry, o Options) (*KeyHint, error)
	StreamMap(ctx context.Context, key []byte, o Options) ([]Entry, error)
	CreateOrderedMap(ctx context.Context, key []byte, data []OrderedEntry, o Options) (*KeyHint, error)
	StreamOrderedMap(ctx context.Context, key []byte, o Options) ([]OrderedEntry, error)
	AddElement(ctx context.Context, key []byte, data []Payload, o Options) (bool, error)
	AddElementOrdered(ctx context.Context, key []byte, data []OrderedPayload, o Options) (bool, error)
	AddElementOrderedSet(ctx context.Context, key []byte, data []OrderedPayload, o Options) (bool, error)
	AddElementToTail(ctx context.Context, key []byte, data []Payload, o Options) (bool, error)
	AddElementToHead(ctx context.Context, key []byte, data []Payload, o Options) (bool, error)
	AddElementToPosition(ctx context.Context, key []byte, data []Payload, pos uint32, o Options) (uint32, error)
	AddElementWithWeight(ctx context.Context, key []byte, data []OrderedPayload, o Options) (uint32, error)
	AddElementToPositionBefore(ctx context.Context, key []byte, data []Payload, pivot Payload, o Options) (bool, error)
	AddElementToPositionAfter(ctx context.Context, key []byte, data []Payload, pivot Payload, o Options) (bool, error)
	AddElementHashMap(ctx context.Context, key []byte, data []Entry, o Options) (uint32, error)
	AddElementOrderedMap(ctx context.Context, key []byte, data []OrderedEntry, o Options) (uint32, error)
	StreamElementInRangeUnordered(ctx context.Context, key []byte, t ContainerType, start, end uint32, o Options) ([]Payload, error)
	StreamElementInRangeOrderedSet(ctx context.Context, key []byte, start, end uint64, reverse bool, o Options) ([]OrderedPayload, error)
	StreamElementInRangeOrdered(ctx context.Context, key []byte, start, end uint64, o Options) ([]OrderedPayload, error)
	Close() error
	Target() string
	DefaultClientID() uint32
	DefaultTimeout() time.Duration
	DefaultTTL() time.Duration
}

var _ Operations = (*Client)(nil)
var _ Operations = (*SmartClient)(nil)
