// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: coordinator.proto

package coordinatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_Init_FullMethodName                     = "/coordinator.CoordinatorService/init"
	CoordinatorService_Ping_FullMethodName                     = "/coordinator.CoordinatorService/ping"
	CoordinatorService_GetRoutingInfo_FullMethodName           = "/coordinator.CoordinatorService/getRoutingInfo"
	CoordinatorService_RemoveRoutingInfo_FullMethodName        = "/coordinator.CoordinatorService/removeRoutingInfo"
	CoordinatorService_SendRoutingInfo_FullMethodName          = "/coordinator.CoordinatorService/sendRoutingInfo"
	CoordinatorService_ReadyForDataMigration_FullMethodName    = "/coordinator.CoordinatorService/readyForDataMigration"
	CoordinatorService_ProvideGlobalRoutingInfo_FullMethodName = "/coordinator.CoordinatorService/provideGlobalRoutingInfo"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceClient interface {
	// init message sent node to neighbours to coordinator  interface
	Init(ctx context.Context, in *PeerAnnounceRequest, opts ...grpc.CallOption) (*PeerAnnounceReply, error)
	Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	GetRoutingInfo(ctx context.Context, in *PeerRoutingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerRouting], error)
	RemoveRoutingInfo(ctx context.Context, in *PeerRoutingRequest, opts ...grpc.CallOption) (*Void, error)
	SendRoutingInfo(ctx context.Context, in *RoutingInfoData, opts ...grpc.CallOption) (*Void, error)
	ReadyForDataMigration(ctx context.Context, in *PeerAnnounceRequest, opts ...grpc.CallOption) (*Void, error)
	ProvideGlobalRoutingInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingInfoData], error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) Init(ctx context.Context, in *PeerAnnounceRequest, opts ...grpc.CallOption) (*PeerAnnounceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerAnnounceReply)
	err := c.cc.Invoke(ctx, CoordinatorService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Ping(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, CoordinatorService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetRoutingInfo(ctx context.Context, in *PeerRoutingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerRouting], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[0], CoordinatorService_GetRoutingInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PeerRoutingRequest, PeerRouting]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_GetRoutingInfoClient = grpc.ServerStreamingClient[PeerRouting]

func (c *coordinatorServiceClient) RemoveRoutingInfo(ctx context.Context, in *PeerRoutingRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, CoordinatorService_RemoveRoutingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) SendRoutingInfo(ctx context.Context, in *RoutingInfoData, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, CoordinatorService_SendRoutingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReadyForDataMigration(ctx context.Context, in *PeerAnnounceRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, CoordinatorService_ReadyForDataMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ProvideGlobalRoutingInfo(ctx context.Context, in *Void, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RoutingInfoData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinatorService_ServiceDesc.Streams[1], CoordinatorService_ProvideGlobalRoutingInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Void, RoutingInfoData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_ProvideGlobalRoutingInfoClient = grpc.ServerStreamingClient[RoutingInfoData]

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
type CoordinatorServiceServer interface {
	// init message sent node to neighbours to coordinator  interface
	Init(context.Context, *PeerAnnounceRequest) (*PeerAnnounceReply, error)
	Ping(context.Context, *Ping) (*Pong, error)
	GetRoutingInfo(*PeerRoutingRequest, grpc.ServerStreamingServer[PeerRouting]) error
	RemoveRoutingInfo(context.Context, *PeerRoutingRequest) (*Void, error)
	SendRoutingInfo(context.Context, *RoutingInfoData) (*Void, error)
	ReadyForDataMigration(context.Context, *PeerAnnounceRequest) (*Void, error)
	ProvideGlobalRoutingInfo(*Void, grpc.ServerStreamingServer[RoutingInfoData]) error
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) Init(context.Context, *PeerAnnounceRequest) (*PeerAnnounceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedCoordinatorServiceServer) Ping(context.Context, *Ping) (*Pong, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetRoutingInfo(*PeerRoutingRequest, grpc.ServerStreamingServer[PeerRouting]) error {
	return status.Error(codes.Unimplemented, "method GetRoutingInfo not implemented")
}
func (UnimplementedCoordinatorServiceServer) RemoveRoutingInfo(context.Context, *PeerRoutingRequest) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRoutingInfo not implemented")
}
func (UnimplementedCoordinatorServiceServer) SendRoutingInfo(context.Context, *RoutingInfoData) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRoutingInfo not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReadyForDataMigration(context.Context, *PeerAnnounceRequest) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadyForDataMigration not implemented")
}
func (UnimplementedCoordinatorServiceServer) ProvideGlobalRoutingInfo(*Void, grpc.ServerStreamingServer[RoutingInfoData]) error {
	return status.Error(codes.Unimplemented, "method ProvideGlobalRoutingInfo not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerAnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Init(ctx, req.(*PeerAnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Ping(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetRoutingInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeerRoutingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServiceServer).GetRoutingInfo(m, &grpc.GenericServerStream[PeerRoutingRequest, PeerRouting]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_GetRoutingInfoServer = grpc.ServerStreamingServer[PeerRouting]

func _CoordinatorService_RemoveRoutingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRoutingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RemoveRoutingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RemoveRoutingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RemoveRoutingInfo(ctx, req.(*PeerRoutingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_SendRoutingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutingInfoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).SendRoutingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_SendRoutingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).SendRoutingInfo(ctx, req.(*RoutingInfoData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReadyForDataMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerAnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReadyForDataMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReadyForDataMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReadyForDataMigration(ctx, req.(*PeerAnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ProvideGlobalRoutingInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServiceServer).ProvideGlobalRoutingInfo(m, &grpc.GenericServerStream[Void, RoutingInfoData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinatorService_ProvideGlobalRoutingInfoServer = grpc.ServerStreamingServer[RoutingInfoData]

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordinator.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "init",
			Handler:    _CoordinatorService_Init_Handler,
		},
		{
			MethodName: "ping",
			Handler:    _CoordinatorService_Ping_Handler,
		},
		{
			MethodName: "removeRoutingInfo",
			Handler:    _CoordinatorService_RemoveRoutingInfo_Handler,
		},
		{
			MethodName: "sendRoutingInfo",
			Handler:    _CoordinatorService_SendRoutingInfo_Handler,
		},
		{
			MethodName: "readyForDataMigration",
			Handler:    _CoordinatorService_ReadyForDataMigration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getRoutingInfo",
			Handler:       _CoordinatorService_GetRoutingInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "provideGlobalRoutingInfo",
			Handler:       _CoordinatorService_ProvideGlobalRoutingInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "coordinator.proto",
}
