// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: coordinator.proto

package coordinatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRole int32

const (
	NodeRole_UNDEFINED NodeRole = 0
	NodeRole_MASTER    NodeRole = 1
	NodeRole_BACKUP    NodeRole = 2
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "UNDEFINED",
		1: "MASTER",
		2: "BACKUP",
	}
	NodeRole_value = map[string]int32{
		"UNDEFINED": 0,
		"MASTER":    1,
		"BACKUP":    2,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[0].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[0]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

type PeerAnnounceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Target            string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	CoordinatorTarget string                 `protobuf:"bytes,2,opt,name=coordinator_target,json=coordinatorTarget,proto3" json:"coordinator_target,omitempty"`
	ReplicatorTarget  string                 `protobuf:"bytes,3,opt,name=replicator_target,json=replicatorTarget,proto3" json:"replicator_target,omitempty"`
	Uptime            uint64                 `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Relay             *string                `protobuf:"bytes,5,opt,name=relay,proto3,oneof" json:"relay,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerAnnounceRequest) Reset() {
	*x = PeerAnnounceRequest{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAnnounceRequest) ProtoMessage() {}

func (x *PeerAnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAnnounceRequest.ProtoReflect.Descriptor instead.
func (*PeerAnnounceRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *PeerAnnounceRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PeerAnnounceRequest) GetCoordinatorTarget() string {
	if x != nil {
		return x.CoordinatorTarget
	}
	return ""
}

func (x *PeerAnnounceRequest) GetReplicatorTarget() string {
	if x != nil {
		return x.ReplicatorTarget
	}
	return ""
}

func (x *PeerAnnounceRequest) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *PeerAnnounceRequest) GetRelay() string {
	if x != nil && x.Relay != nil {
		return *x.Relay
	}
	return ""
}

type PeerAnnounceReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Target            string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	CoordinatorTarget string                 `protobuf:"bytes,2,opt,name=coordinator_target,json=coordinatorTarget,proto3" json:"coordinator_target,omitempty"`
	ReplicatorTarget  string                 `protobuf:"bytes,3,opt,name=replicator_target,json=replicatorTarget,proto3" json:"replicator_target,omitempty"`
	Uptime            uint64                 `protobuf:"varint,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerAnnounceReply) Reset() {
	*x = PeerAnnounceReply{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAnnounceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAnnounceReply) ProtoMessage() {}

func (x *PeerAnnounceReply) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAnnounceReply.ProtoReflect.Descriptor instead.
func (*PeerAnnounceReply) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *PeerAnnounceReply) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PeerAnnounceReply) GetCoordinatorTarget() string {
	if x != nil {
		return x.CoordinatorTarget
	}
	return ""
}

func (x *PeerAnnounceReply) GetReplicatorTarget() string {
	if x != nil {
		return x.ReplicatorTarget
	}
	return ""
}

func (x *PeerAnnounceReply) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type Ping struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Target            string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	CoordinatorTarget string                 `protobuf:"bytes,2,opt,name=coordinator_target,json=coordinatorTarget,proto3" json:"coordinator_target,omitempty"`
	Uptime            uint64                 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Ping) GetCoordinatorTarget() string {
	if x != nil {
		return x.CoordinatorTarget
	}
	return ""
}

func (x *Ping) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type Pong struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Target            string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	CoordinatorTarget string                 `protobuf:"bytes,2,opt,name=coordinator_target,json=coordinatorTarget,proto3" json:"coordinator_target,omitempty"`
	Uptime            uint64                 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Pong) GetCoordinatorTarget() string {
	if x != nil {
		return x.CoordinatorTarget
	}
	return ""
}

func (x *Pong) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type PeerRouting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Role          NodeRole               `protobuf:"varint,2,opt,name=role,proto3,enum=coordinator.NodeRole" json:"role,omitempty"`
	PartitionIds  []uint32               `protobuf:"varint,3,rep,packed,name=partitionIds,proto3" json:"partitionIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRouting) Reset() {
	*x = PeerRouting{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRouting) ProtoMessage() {}

func (x *PeerRouting) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRouting.ProtoReflect.Descriptor instead.
func (*PeerRouting) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *PeerRouting) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PeerRouting) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_UNDEFINED
}

func (x *PeerRouting) GetPartitionIds() []uint32 {
	if x != nil {
		return x.PartitionIds
	}
	return nil
}

type PeerRoutingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRoutingRequest) Reset() {
	*x = PeerRoutingRequest{}
	mi := &file_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRoutingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRoutingRequest) ProtoMessage() {}

func (x *PeerRoutingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRoutingRequest.ProtoReflect.Descriptor instead.
func (*PeerRoutingRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *PeerRoutingRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type RoutingInfoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxShards     uint32                 `protobuf:"varint,1,opt,name=max_shards,json=maxShards,proto3" json:"max_shards,omitempty"`
	PeerRouting   []*PeerRouting         `protobuf:"bytes,2,rep,name=peerRouting,proto3" json:"peerRouting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingInfoData) Reset() {
	*x = RoutingInfoData{}
	mi := &file_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingInfoData) ProtoMessage() {}

func (x *RoutingInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingInfoData.ProtoReflect.Descriptor instead.
func (*RoutingInfoData) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *RoutingInfoData) GetMaxShards() uint32 {
	if x != nil {
		return x.MaxShards
	}
	return 0
}

func (x *RoutingInfoData) GetPeerRouting() []*PeerRouting {
	if x != nil {
		return x.PeerRouting
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{7}
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vcoordinator\"\xc6\x01\n" +
	"\x13PeerAnnounceRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12-\n" +
	"\x12coordinator_target\x18\x02 \x01(\tR\x11coordinatorTarget\x12+\n" +
	"\x11replicator_target\x18\x03 \x01(\tR\x10replicatorTarget\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x04R\x06uptime\x12\x19\n" +
	"\x05relay\x18\x05 \x01(\tH\x00R\x05relay\x88\x01\x01B\b\n" +
	"\x06_relay\"\x9f\x01\n" +
	"\x11PeerAnnounceReply\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12-\n" +
	"\x12coordinator_target\x18\x02 \x01(\tR\x11coordinatorTarget\x12+\n" +
	"\x11replicator_target\x18\x03 \x01(\tR\x10replicatorTarget\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\x04R\x06uptime\"e\n" +
	"\x04Ping\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12-\n" +
	"\x12coordinator_target\x18\x02 \x01(\tR\x11coordinatorTarget\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x04R\x06uptime\"e\n" +
	"\x04Pong\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12-\n" +
	"\x12coordinator_target\x18\x02 \x01(\tR\x11coordinatorTarget\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x04R\x06uptime\"t\n" +
	"\vPeerRouting\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.coordinator.NodeRoleR\x04role\x12\"\n" +
	"\fpartitionIds\x18\x03 \x03(\rR\fpartitionIds\",\n" +
	"\x12PeerRoutingRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"l\n" +
	"\x0fRoutingInfoData\x12\x1d\n" +
	"\n" +
	"max_shards\x18\x01 \x01(\rR\tmaxShards\x12:\n" +
	"\vpeerRouting\x18\x02 \x03(\v2\x18.coordinator.PeerRoutingR\vpeerRouting\"\x06\n" +
	"\x04Void*1\n" +
	"\bNodeRole\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\n" +
	"\n" +
	"\x06MASTER\x10\x01\x12\n" +
	"\n" +
	"\x06BACKUP\x10\x022\x93\x04\n" +
	"\x12CoordinatorService\x12J\n" +
	"\x04init\x12 .coordinator.PeerAnnounceRequest\x1a\x1e.coordinator.PeerAnnounceReply\"\x00\x12.\n" +
	"\x04ping\x12\x11.coordinator.Ping\x1a\x11.coordinator.Pong\"\x00\x12O\n" +
	"\x0egetRoutingInfo\x12\x1f.coordinator.PeerRoutingRequest\x1a\x18.coordinator.PeerRouting\"\x000\x01\x12I\n" +
	"\x11removeRoutingInfo\x12\x1f.coordinator.PeerRoutingRequest\x1a\x11.coordinator.Void\"\x00\x12D\n" +
	"\x0fsendRoutingInfo\x12\x1c.coordinator.RoutingInfoData\x1a\x11.coordinator.Void\"\x00\x12N\n" +
	"\x15readyForDataMigration\x12 .coordinator.PeerAnnounceRequest\x1a\x11.coordinator.Void\"\x00\x12O\n" +
	"\x18provideGlobalRoutingInfo\x12\x11.coordinator.Void\x1a\x1c.coordinator.RoutingInfoData\"\x000\x01B~\n" +
	"\x1fcom.hurricache.grpc.coordinatorB\vcoordinatorP\x01Z>github.com/hurricache/hurricache-go-client/proto/coordinatorpb\xa2\x02\vcoordinatorb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_coordinator_proto_goTypes = []any{
	(NodeRole)(0),               // 0: coordinator.NodeRole
	(*PeerAnnounceRequest)(nil), // 1: coordinator.PeerAnnounceRequest
	(*PeerAnnounceReply)(nil),   // 2: coordinator.PeerAnnounceReply
	(*Ping)(nil),                // 3: coordinator.Ping
	(*Pong)(nil),                // 4: coordinator.Pong
	(*PeerRouting)(nil),         // 5: coordinator.PeerRouting
	(*PeerRoutingRequest)(nil),  // 6: coordinator.PeerRoutingRequest
	(*RoutingInfoData)(nil),     // 7: coordinator.RoutingInfoData
	(*Void)(nil),                // 8: coordinator.Void
}
var file_coordinator_proto_depIdxs = []int32{
	0, // 0: coordinator.PeerRouting.role:type_name -> coordinator.NodeRole
	5, // 1: coordinator.RoutingInfoData.peerRouting:type_name -> coordinator.PeerRouting
	1, // 2: coordinator.CoordinatorService.init:input_type -> coordinator.PeerAnnounceRequest
	3, // 3: coordinator.CoordinatorService.ping:input_type -> coordinator.Ping
	6, // 4: coordinator.CoordinatorService.getRoutingInfo:input_type -> coordinator.PeerRoutingRequest
	6, // 5: coordinator.CoordinatorService.removeRoutingInfo:input_type -> coordinator.PeerRoutingRequest
	7, // 6: coordinator.CoordinatorService.sendRoutingInfo:input_type -> coordinator.RoutingInfoData
	1, // 7: coordinator.CoordinatorService.readyForDataMigration:input_type -> coordinator.PeerAnnounceRequest
	8, // 8: coordinator.CoordinatorService.provideGlobalRoutingInfo:input_type -> coordinator.Void
	2, // 9: coordinator.CoordinatorService.init:output_type -> coordinator.PeerAnnounceReply
	4, // 10: coordinator.CoordinatorService.ping:output_type -> coordinator.Pong
	5, // 11: coordinator.CoordinatorService.getRoutingInfo:output_type -> coordinator.PeerRouting
	8, // 12: coordinator.CoordinatorService.removeRoutingInfo:output_type -> coordinator.Void
	8, // 13: coordinator.CoordinatorService.sendRoutingInfo:output_type -> coordinator.Void
	8, // 14: coordinator.CoordinatorService.readyForDataMigration:output_type -> coordinator.Void
	7, // 15: coordinator.CoordinatorService.provideGlobalRoutingInfo:output_type -> coordinator.RoutingInfoData
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	file_coordinator_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		EnumInfos:         file_coordinator_proto_enumTypes,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
